version: '3.9'

networks:
  wp_dev_network:
    driver: bridge

services:
  db:
    container_name: dev-wp-db-container
    build:
      context: .
      dockerfile: mariadb-dockerfile
    ports:
      - 3306:3306
    command: --max_allowed_packet=256M
    volumes:
      - ./app/mysql:/var/lib/mysql:rw
      - ./app/logs:/var/log/mysql:rw
    restart: always
    networks:
      - wp_dev_network

  litespeed_webserver:
    # Webadmin (localhost:7080) admin/my_password
    container_name: dev-wp-litespeed-container
    build:
      context: .
      dockerfile: litespeed83-dockerfile
      # dockerfile: litespeed82-dockerfile
      # dockerfile: litespeed81-dockerfile
      # dockerfile: litespeed74-dockerfile
    volumes:
       - ./app/public_html:/var/www/vhosts/localhost/html
       - ./app/logs:/usr/local/lsws/logs/
    ports:
      - 80:80
      - 7080:7080
    restart: always
    networks:
      - wp_dev_network

  litespeed_memcache:
    container_name: dev-wp-lsmcd-container
    build:
      context: .
      dockerfile: lsmcd-dockerfile
      shm_size: 128mb
    shm_size: 128mb # enough for LSMCD to start
    ports:
      - 11211:11211
    restart: always
    networks:
      - wp_dev_network

  phpmyadmin:
    # localhost:8081 root/MYSQL_ROOT_PASSWORD
    container_name: dev-wp-phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 192M
      MAX_EXECUTION_TIME: 600
    depends_on:
      - db
    restart: always
    networks:
      - wp_dev_network
