volumes:
  lsmcd_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=128m,uid=1000,gid=1000,mode=1777
  db_data:
    driver: local

services:
  # Database Service
  db:
    container_name: db-container
    build:
      context: dockerfiles
      dockerfile: mariadb
      args:
        DB_VERSION: ${DB_VERSION}
        MYSQL_PORT: ${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Europe/Moscow
    ports:
      - ${MYSQL_PORT}:3306
    command: --max_allowed_packet=512M
    volumes:
      - db_data:/var/lib/mysql:rw,delegated
      - ./app/logs:/var/log/mysql:rw,delegated
    restart: always
    networks:
      - wp_dev_network
    logging:
      driver: json-file
      options:
        max-size: 3m
        max-file: 3
    deploy:
      resources:
        limits:
          cpus: 2.00
          memory: 1G
        reservations:
          cpus: 1.00
          memory: 0.5G
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true

  # LiteSpeed Web Server Service
  litespeed_webserver:
    container_name: litespeed-container
    build:
      context: dockerfiles
      dockerfile: litespeed
      args:
        OLS_VERSION: ${OLS_VERSION}
        PHP_VERSION: ${PHP_VERSION}
        WEBADMIN_LOGIN: ${WEBADMIN_LOGIN}
        WEBADMIN_PASSWORD: ${WEBADMIN_PASSWORD}
    ports:
      - ${HTTP_PORT}:80
      - ${WEBADMIN_PORT}:7080
    volumes:
      - ./app/public_html:/var/www/vhosts/localhost/html:rw,cached
      - ./app/logs:/usr/local/lsws/logs/:rw,delegated
    restart: always
    networks:
      - wp_dev_network
    logging:
      driver: json-file
      options:
        max-size: 3m
        max-file: 3
    deploy:
      resources:
        limits:
          cpus: 2.00
          memory: 1G
        reservations:
          cpus: 1.00
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true

  # LiteSpeed Memcached Service
  litespeed_memcache:
    container_name: lsmcd-container
    build:
      context: dockerfiles
      dockerfile: lsmcd
      args:
        LSMCD_USER: ${LSMCD_USER}
        LSMCD_PASSWORD: ${LSMCD_PASSWORD}
        LSMCD_PORT: ${LSMCD_PORT}
    ports:
      - ${LSMCD_PORT}:${LSMCD_PORT}
    volumes:
      - lsmcd_data:/dev/shm/lsmcd:rw,delegated
    shm_size: 256mb
    restart: always
    networks:
      - wp_dev_network
    logging:
      driver: json-file
      options:
        max-size: 3m
        max-file: 3
    deploy:
      resources:
        limits:
          cpus: 1.00
          memory: 0.5G
        reservations:
          cpus: 0.25
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "pgrep lsmcdctrl || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true

  # phpMyAdmin Service (for development only)
  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 192M
      MAX_EXECUTION_TIME: 600
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - wp_dev_network
    logging:
      driver: json-file
      options:
        max-size: 3m
        max-file: 3
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    security_opt:
      - no-new-privileges:true

networks:
  wp_dev_network:
    driver: bridge

# TODO
# - Change litespeed_webserver error log to NOTICE level
# - Add non-root user for all the containers
# - Add multisite support for litespeed_webserver
# - Add certbot container for SSL certificates
# - ?Add a cron job for database backups
# - ?Add a cron job for log rotation
# - ?Add a cron job for LSMCD cache cleanup
# - ?Add monitoring tools like Prometheus and Grafana
# - ?Switch to Redis for object caching
