# https://hub.docker.com/_/ubuntu/
FROM ubuntu:jammy

# Install OS packages
RUN apt-get update -y && \
    apt-get install htop nano sudo -y && \
    apt-get install git build-essential zlib1g-dev libexpat1-dev openssl libssl-dev libsasl2-dev libpcre3-dev -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install LSMCD (LiteSpeed Memcached)
# https://docs.litespeedtech.com/products/lsmcd/getting_started/
RUN git clone https://github.com/litespeedtech/lsmcd.git
RUN cd lsmcd && \
    bash fixtimestamp.sh && \
    bash configure CFLAGS=" -O3" CXXFLAGS=" -O3" && \
    make && \
    cd dist && \
    sed -i 's/chkconfig/update-rc.d/g' install.sh && \
    bash install.sh
RUN chmod -R 777 /usr/local/lsmcd

# CACHED.USESASL=TRUE
# IMPORTANT IN WP-Admin SET litespeed_memcache instead of the localhost hostname
RUN sed -i 's/Cached.UseSasl=false/Cached.UseSasl=true/g' /usr/local/lsmcd/conf/node.conf && \
# Cached.Anonymous=true
    sed -i 's/Cached.Anonymous=false/Cached.Anonymous=true/g' /usr/local/lsmcd/conf/node.conf && \
# CACHED.ADDR=0.0.0.0:11211 to make it worknot just inside the container
    sed -i 's/CACHED.ADDR=127.0.0.1:11211/CACHED.ADDR=0.0.0.0:11211/g' /usr/local/lsmcd/conf/node.conf && \
    rm -rf /dev/shm/lsmcd

EXPOSE 11211

CMD /usr/local/lsmcd/bin/lsmcdctrl start && sleep infinity
# Service runs the command: /usr/local/lsmcd/bin/lsmcdctrl start, LOG: /tmp/lsmcd.log
# Config /usr/local/lsmcd/conf/node.conf
